### ISSUE TITLE
lp_normalization.py implementation is not right

### ISSUE THREAD

**Issue by wutiantong** [onnx/onnx-tensorflow#465] opened 2019-07-15 09:10 UTC
Currently, the implementation is equal to `tf.norm()`, which is ReduceL2 actually.

Totally speaking, lp_normalization should be `tf.div(X, tf.norm(X))`.

**Comment by chinhuang007** [comment] 2019-07-16 18:46
Thanks for pointing it out. Will look into a fix.

**Comment by chinhuang007** [comment] 2019-10-01 23:07
The fix is merged. Please go ahead and verify. Reopen if the problem is not addressed.

**Closed by chinhuang007** 2019-10-01 23:07 UTC
