### ISSUE TITLE
ModuleNotFoundError: No module named 'onnx.onnx_pb2'

### ISSUE THREAD

**Issue by cl5220418** [onnx/onnx-tensorflow#145] opened 2018-05-02 11:19 UTC
When I run an example "relu.py", this error occurs. What should I do?

> Traceback (most recent call last):
  File "relu.py", line 6, in <module>
    from onnx_tf.backend import run_node, prepare
  File "/home/cl/anaconda3/envs/caffe2/lib/python3.6/site-packages/onnx_tf/backend.py", line 24, in <module>
    from onnx.onnx_pb2 import GraphProto, TensorProto, AttributeProto
ModuleNotFoundError: No module named 'onnx.onnx_pb2'

**Comment by fumihwh** [comment] 2018-05-02 11:42
Did you install onnx?

**Comment by greenwaves** [comment] 2018-05-02 16:03
Hi, I'm having the same issue. I performed the following steps for the installation: 

API: onnx-tensorflow backend
OS: Ubuntu 17.10
Python version: Python 2.7.14
Steps to reproduce:
4 sudo apt-get install protobuf-compiler libprotoc-dev
5 pip install onnx
6 sudo apt-get install python-pip
7 pip install onnx
8 python -c "import onnx"
9 pip install pytest-cov nbval
10 pytest
11 ls
12 pytest
13 sudo apt-get install python-pip python-dev
14 pip install tensorflow
15 python
16 git clone git@github.com:onnx/onnx-tensorflow.git
17 sudo git clone git@github.com:onnx/onnx-tensorflow.git
18 git clone https://github.com/onnx/onnx-tensorflow.git
19 cd onnx-tensorflow
20 pip install -e .

When running the relu.py example in onnx-tensorflow/example, I get the following message:

$ python relu.py
Traceback (most recent call last):
File "relu.py", line 6, in 
from onnx_tf.backend import run_node, prepare
File "/home/corine_lamagdeleine/onnx-tensorflow/onnx_tf/init.py", line 1, in 
from . import frontend
File "/home/corine_lamagdeleine/onnx-tensorflow/onnx_tf/frontend.py", line 37, in 
from onnx.onnx_pb2 import TensorProto
ImportError: No module named onnx_pb2

Any clue to solve this problem?

Corine

**Comment by tjingrant** [comment] 2018-05-02 16:37
I think they may have renamed the namespace encapsulating these protpbuf definitions.

**Comment by tjingrant** [comment] 2018-05-02 16:38
c.f. this commit: https://github.com/onnx/onnx/commit/1d81b19ab70a148e08ee75eee1fff4e98df5f990

**Comment by fumihwh** [comment] 2018-05-03 01:34
Can avoid by installing onnx from source for temporally.
PR I referenced is a fix.

**Comment by cl5220418** [comment] 2018-05-03 02:14
Thanks. This problem was solved, but I found the following questions when I run this code. What should I do?

>  File "test_model_large_stepping.py", line 10, in <module>
    import onnx_caffe2.backend as c2
ModuleNotFoundError: No module named 'onnx_caffe2'

**Comment by tjingrant** [comment] 2018-05-11 05:10
Seems like the issue is fixed, closing.

**Closed by tjingrant** 2018-05-11 05:10 UTC
