### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal

### ISSUE THREAD

**Issue by jaggernaut007** [onnx/onnx-tensorflow#618] opened 2020-05-17 08:32 UTC
**Describe the bug**

Getting this error while converting onnx to tensorflow.
this model works fine on pytorch. Seems like there is an issue with the layer 134.

**To Reproduce**

```
import onnx

from onnx_tf.backend import prepare

onnx_model = onnx.load("../margipose/pretrained/margipose2.onnx")  # load onnx model
tf_rep = prepare(onnx_model)  # prepare tf representation
tf_rep.export_graph("output_path")  # export the model
```

If a model exported from PyTorch and Caffe2 is having trouble in ONNX-TF, use the next section to attach the model.

**ONNX model file**

Link to the Py torch model 
https://cloudstor.aarnet.edu.au/plus/s/fg5CCss8o9PdURs

Link to onnx model
https://drive.google.com/file/d/1_o_6Gg6arMN4CqKEvaaNPQ-jI3fbcbIV/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.8
 - ONNX version: 1.7
 - ONNX-TF version: 1.5
 - Tensorflow version: 2.2

**Additional context**

Traceback (most recent call last):
  File "example/onnx_to_tf.py", line 6, in <module>
    tf_rep = prepare(onnx_model)  # prepare tf representation
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    output_ops = cls._onnx_node_to_tensorflow_op(onnx_node,
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/backend.py", line 249, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/handlers/backend/add.py", line 23, in version_7
    return [cls.make_tensor_from_onnx_node(node, **kwargs)]
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/home/shreyas/onnx/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 181, in _run_tf_func
    return tf_func(*inputs,
  File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 346, in add
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
    ret = Operation(
  File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1816, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,
  File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1657, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 32 and 33 for '{{node Add_135}} = Add[T=DT_FLOAT](Relu_132, BatchNormalization_134/add_1)' with input shapes: [1,128,32,32], [1,128,33,33].

**Comment by chinhuang007** [comment] 2020-05-21 01:36
Thanks for reporting this issue. The problem is coming from a conv transpose node, leading to the shape mismatch for add node. A PR is created. Feel free to check it out before it is reviewed and merged.

**Comment by jaggernaut007** [comment] 2020-05-21 07:23
This works great|! Thanks for the fix @chinhuang007 . Appreciate it!

**Closed** 2020-05-21 07:24 UTC

**Comment by Ark-kun** [comment] 2021-03-18 09:26
There is still a problem with dimensions.
I cannot convert a simple dense network from PyTorch to Tensorflow through ONNX.

>ValueError: Dimensions must be equal, but are 1 and 7 for '{{node onnx_tf_prefix_If_4/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](onnx_tf_prefix_If_4/flatten/ExpandDims, onnx_tf_prefix_If_4/transpose)' with input shapes: [7,1], [7,100].

onnx-tf==1.7.0
onnx==1.8.0
tensorflow==2.4.1
