### ISSUE TITLE
SSD ONNX Model not able to pass onnx_tf.backend.prepare

### ISSUE THREAD

**Issue by rit7897** [onnx/onnx-tensorflow#599] opened 2020-03-23 14:40 UTC
Hi the ssd onnx model is thowing out error of ValueError: None values not supported, when i ran onnx_tf.backend.prepare.
please help me out
![Screenshot from 2020-03-23 20-09-28](https://user-images.githubusercontent.com/15844690/77328209-3dc7e100-6d42-11ea-9466-c0e207bb335d.png)

**Comment by chinhuang007** [comment] 2020-05-29 22:06
@rit7897 Looks like slice is not handling dynamic input shape. Can you please provide the onnx file?

**Comment by chinhuang007** [comment] 2020-05-29 22:13
Just checked and believe the slice issue was fixed by this PR https://github.com/onnx/onnx-tensorflow/pull/543. If you want, please verify with an onnx-tf build from source using the master branch and TF 2.x.

**Comment by chinhuang007** [comment] 2020-06-05 23:29
Close because the issue is fixed.

**Closed by chinhuang007** 2020-06-05 23:29 UTC
