### ISSUE TITLE
FER+ Emotion Recognition : Cannot Run the Model: gives Error : Negative dimension size caused by subtracting 3 from 1

### ISSUE THREAD

**Issue by surajkandukuri** [onnx/onnx-tensorflow#502] opened 2019-09-09 02:50 UTC
I tried to implement the FER+ Emotion Recognition model in the system with configuration 
System : Ubuntu 18.04
Tensorflow- gpu : 1.14.0
Keras: 2.2.5
Python: 3.6.8 
  
    
[Error in Onnx FER+.docx](https://github.com/onnx/models/files/3588474/Error.in.Onnx.FER%2B.docx)

**Comment by prasanthpul** [comment] 2019-09-09 18:30
transferred this issue to onnx-tensorflow repo as the problem seems to be with the ONNX to TF converter rather than the model. the model has previously been verified with [ONNX Runtime](https://github.com/microsoft/onnxruntime).

**Comment by chinhuang007** [comment] 2019-09-09 19:04
@prasanthpul Thanks for transferring the issue. @ebarsoum Sure, I will take a look.

**Comment by chinhuang007** [comment] 2019-09-10 01:36
@surajkandukuri Can you provide 1.jpg so we are using exact same input to verify and debug?

**Comment by surajkandukuri** [comment] 2019-09-10 02:21
@chinhuang007 sure. Please find the attached. 
![1](https://user-images.githubusercontent.com/20826129/64579223-b38cd200-d347-11e9-8a11-997ba0e87858.jpg)

**Comment by chinhuang007** [comment] 2019-11-05 00:53
The issue is addressed by PR #504

**Closed by chinhuang007** 2019-11-05 00:53 UTC
