### ISSUE TITLE
NotImplementedError: Rsqrt op is not implemented.

### ISSUE THREAD

**Issue by lygstate** [onnx/onnx-tensorflow#240] opened 2018-08-24 12:00 UTC
File "E:\CI-Cor-Ready\ai\face-io\webdnn\scripts\venv\lib\site-packages\onnx_tf\frontend.py", line 442, in tensorflow_graph_to_onnx_model
    graph_def, output_node, opset, graph_name, ignore_unimplemented)
  File "E:\CI-Cor-Ready\ai\face-io\webdnn\scripts\venv\lib\site-packages\onnx_tf\frontend.py", line 294, in tensorflow_graph_to_onnx_graph
    "{} op is not implemented.".format(node.op))
  File "E:\CI-Cor-Ready\ai\face-io\webdnn\scripts\venv\lib\site-packages\onnx_tf\frontend.py", line 531, in _catch_exception
    raise exception(message)
NotImplementedError: Rsqrt op is not implemented.

**Comment by fumihwh** [comment] 2018-09-02 23:50
Yes, Rsqrt is not an ONNX operator. It will not be supported by other frameworks.
If you even want to export it, try `ignore_unimplemented`.

**Comment by tjingrant** [comment] 2018-09-09 18:57
Closing as a duplicate of https://github.com/onnx/onnx-tensorflow/issues/86.

**Closed by tjingrant** 2018-09-09 18:57 UTC
