### ISSUE TITLE
bidirectional lstm model with initial_h and initial_c will get wrong result

### ISSUE THREAD

**Issue by fjfjfan** [onnx/onnx-tensorflow#409] opened 2019-04-17 07:16 UTC
**Describe the bug**

bidirectional lstm model with initial_h and initial_c will get wrong result

**To Reproduce**
```
import onnx
import numpy as np
from onnx_tf.backend import run_node

input = np.array([[[1., 2., 3., 4.], [5., 6., 7., 8.]]]).astype(np.float32)

input_size = 4
hidden_size = 3
weight_scale = 0.1
number_of_gates = 4
number_of_peepholes = 3

# Initializing Inputs
X = input
W = weight_scale * np.ones((2, number_of_gates * hidden_size, input_size)).astype(np.float32)
R = weight_scale * np.ones((2, number_of_gates * hidden_size, hidden_size)).astype(np.float32)
B = np.zeros((2, 2 * number_of_gates * hidden_size)).astype(np.float32)
sequence_lens = np.repeat(input.shape[0], input.shape[1]).astype(np.int32)
initial_h = weight_scale * np.zeros((2, input.shape[1], hidden_size)).astype(np.float32)
initial_c = weight_scale * np.ones(
    (2, input.shape[1], hidden_size)).astype(np.float32)

node = onnx.helper.make_node(
    'LSTM',
    inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h', 'initial_c'],
    outputs=['Y', 'Y_h', 'Y_c'],
    activations=['Sigmoid', 'Tanh', 'Tanh', 'Sigmoid', 'Tanh', 'Tanh'],
    direction='bidirectional',
    hidden_size=hidden_size)

outputs = run_node(node, [X, W, R, B, sequence_lens, initial_h, initial_c])
```
[test_lstm_bidirectional_c_simple.onnx.zip](https://github.com/onnx/onnx-tensorflow/files/3088296/test_lstm_bidirectional_c_simple.onnx.zip)

Root cause is 

https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/handlers/backend/lstm.py#L166

initial_state_bw = initial_state = (tf.nn.rnn_cell.LSTMStateTuple(
                initial_c[1], initial_h[1]),)
should be modified to 
initial_state_bw = (tf.nn.rnn_cell.LSTMStateTuple(
                initial_c[1], initial_h[1]),)

**Comment by chinhuang007** [comment] 2019-05-10 18:41
Close since the issue is fixed with https://github.com/chinhuang007/onnx-tensorflow/commit/d67e7307d6cf9364a409a0ed776289635ebed698

**Closed** 2019-05-10 18:43 UTC
