### ISSUE TITLE
Build Failure on pip install onnx-tf

### ISSUE THREAD

**Issue by supmit13** [onnx/onnx-tensorflow#346] opened 2019-01-02 08:59 UTC
I tried installing it on Ubuntu 18.04 using pip but it failed with the following error.

-- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-1e138oou/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-1e138oou/onnx/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-1e138oou/onnx/setup.py", line 328, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/home/user/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/home/user/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/user/miniconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/user/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-1e138oou/onnx/setup.py", line 203, in run
      self.run_command('cmake_build')
    File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-1e138oou/onnx/setup.py", line 190, in run
      subprocess.check_call(cmake_args)
    File "/home/user/miniconda3/lib/python3.7/subprocess.py", line 328, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/user/miniconda3/include/python3.7m', '-DPYTHON_EXECUTABLE=/home/user/miniconda3/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-x86_64-linux-gnu.so', '/tmp/pip-install-1e138oou/onnx']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
  Running setup.py install for onnx ... error
    Complete output from command /home/user/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1e138oou/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-squ5k63u/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:17 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-1e138oou/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-1e138oou/onnx/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1e138oou/onnx/setup.py", line 328, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/home/user/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/user/miniconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/user/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-1e138oou/onnx/setup.py", line 203, in run
        self.run_command('cmake_build')
      File "/home/user/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-1e138oou/onnx/setup.py", line 190, in run
        subprocess.check_call(cmake_args)
      File "/home/user/miniconda3/lib/python3.7/subprocess.py", line 328, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/user/miniconda3/include/python3.7m', '-DPYTHON_EXECUTABLE=/home/user/miniconda3/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-x86_64-linux-gnu.so', '/tmp/pip-install-1e138oou/onnx']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/home/user/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1e138oou/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-squ5k63u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1e138oou/onnx/

**Comment by tjingrant** [comment] 2019-01-02 15:56
@supmit13 this is an onnx installation error, not an onnx-tf issue per se. If you search through your log, you haven't even gotten to the stage of installing onnx-tf yet.

From the log, I'm guessing that this line indicates the cause:
> -- The CXX compiler identification is unknown
Maybe you can try explicitly setting the C++ compiler to a known working one by:
` export CXX=[path to a c++ compiler like g++] `

If that doesn't work, it's better to take this issue to onnx main repo.

**Comment by tjingrant** [comment] 2019-01-06 05:34
Closing as it's not really related to onnx-tf.

**Closed by tjingrant** 2019-01-06 05:34 UTC

**Comment by supmit13** [comment] 2019-01-06 15:58
Sure, thanks for the reply.

Thanks and Regards,
Supriyo
