### ISSUE TITLE
LSTM model only has initial_h but no initial_c will get wrong result.

### ISSUE THREAD

**Issue by fjfjfan** [onnx/onnx-tensorflow#408] opened 2019-04-15 09:04 UTC
**Describe the bug**

From:
https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/handlers/backend/lstm.py#L160
seems onnx-tf could just handle the lstm model with(or without) both initial_h and initial_c?
The lstm model only has initial_h will get wrong result.

**To Reproduce**
```
import onnx
import numpy as np
from onnx_tf.backend import run_node, prepare

class LSTM_Helper():
    def __init__(self, **params):  # type: (*Any) -> None
        # LSTM Input Names
        X = str('X')
        W = str('W')
        R = str('R')
        B = str('B')
        H_0 = str('initial_h')
        C_0 = str('initial_c')
        P = str('P')
        number_of_gates = 4
        number_of_peepholes = 3

        required_inputs = [X, W, R]
        for i in required_inputs:
            assert i in params, "Missing Required Input: {0}".format(i)

        self.num_directions = params[W].shape[0]

        if self.num_directions == 1:
            for k in params.keys():
                if k != X:
                    params[k] = np.squeeze(params[k], axis=0)

            hidden_size = params[R].shape[-1]
            batch_size = params[X].shape[1]

            b = params[B] if B in params else np.zeros(2 * number_of_gates * hidden_size, dtype=np.float32)
            p = params[P] if P in params else np.zeros(number_of_peepholes * hidden_size, dtype=np.float32)
            h_0 = params[H_0] if H_0 in params else np.zeros((batch_size, hidden_size), dtype=np.float32)
            c_0 = params[C_0] if C_0 in params else np.zeros((batch_size, hidden_size), dtype=np.float32)

            self.X = params[X]
            self.W = params[W]
            self.R = params[R]
            self.B = b
            self.P = p
            self.H_0 = h_0
            self.C_0 = c_0
        else:
            raise NotImplementedError()

    def f(self, x):  # type: (np.ndarray) -> np.ndarray
        return 1 / (1 + np.exp(-x))

    def g(self, x):  # type: (np.ndarray) -> np.ndarray
        return np.tanh(x)

    def h(self, x):  # type: (np.ndarray) -> np.ndarray
        return np.tanh(x)

    def step(self):  # type: () -> Tuple[np.ndarray, np.ndarray]
        [p_i, p_o, p_f] = np.split(self.P, 3)
        h_list = []
        H_t = self.H_0
        C_t = self.C_0
        for x in np.split(self.X, self.X.shape[0], axis=0):
            gates = np.dot(x, np.transpose(self.W)) + np.dot(H_t, np.transpose(self.R)) + np.add(
                *np.split(self.B, 2))
            i, o, f, c = np.split(gates, 4, -1)
            i = self.f(i + p_i * C_t)
            f = self.f(f + p_f * C_t)
            c = self.g(c)
            C = f * C_t + i * c
            o = self.f(o + p_o * C)
            H = o * self.h(C)
            h_list.append(H)
            H_t = H
            C_t = C
        concatenated = np.concatenate(h_list)
        if self.num_directions == 1:
            output = np.expand_dims(concatenated, 1)
        return output, h_list[-1]

input = np.array([[[1., 2., 3., 4.], [5., 6., 7., 8.]]]).astype(np.float32)

input_size = 4
hidden_size = 3
weight_scale = 0.1
number_of_gates = 4
number_of_peepholes = 3

node = onnx.helper.make_node(
    'LSTM',
    inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h'],
    outputs=['', 'Y'],
    hidden_size=hidden_size
)

# Initializing Inputs
X = input
W = weight_scale * np.ones((1, number_of_gates * hidden_size, input_size)).astype(np.float32)
R = weight_scale * np.ones((1, number_of_gates * hidden_size, hidden_size)).astype(np.float32)
B = np.zeros((1, 2 * number_of_gates * hidden_size)).astype(np.float32)
seq_lens = np.repeat(input.shape[0], input.shape[1]).astype(np.int32)
init_h = weight_scale * np.ones((1, input.shape[1], hidden_size)).astype(np.float32)

lstm = LSTM_Helper(X=X, W=W, R=R, B=B, initial_h=init_h)
_, Y_h_1 = lstm.step()

node = onnx.helper.make_node(
'LSTM',
inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h'],
outputs=['Y', 'Y_h', 'Y_c'],
hidden_size=hidden_size)

outputs = run_node(node, [X, W, R, B, seq_lens, init_h])
Y_h_2 = outputs["Y_h"]

Y_h_1_flattened = Y_h_1.flatten()
Y_h_2_flattened = Y_h_2.flatten()
absolute_error = np.abs(Y_h_1_flattened - Y_h_2_flattened)
max_rerr = np.max(absolute_error)
print("Y_h_1 == Y_h_2? " + str(max_rerr < 0.001))
```
result:
`Y_h_1 == Y_h_2? False`

**Comment by fjfjfan** [comment] 2019-04-16 03:14
while with both initial_h and initial_c will get the right result. 

```
import onnx
import numpy as np
from onnx_tf.backend import run_node, prepare

class LSTM_Helper():
    def __init__(self, **params):  # type: (*Any) -> None
        # LSTM Input Names
        X = str('X')
        W = str('W')
        R = str('R')
        B = str('B')
        H_0 = str('initial_h')
        C_0 = str('initial_c')
        P = str('P')
        number_of_gates = 4
        number_of_peepholes = 3

        required_inputs = [X, W, R]
        for i in required_inputs:
            assert i in params, "Missing Required Input: {0}".format(i)

        self.num_directions = params[W].shape[0]

        if self.num_directions == 1:
            for k in params.keys():
                if k != X:
                    params[k] = np.squeeze(params[k], axis=0)

            hidden_size = params[R].shape[-1]
            batch_size = params[X].shape[1]

            b = params[B] if B in params else np.zeros(2 * number_of_gates * hidden_size, dtype=np.float32)
            p = params[P] if P in params else np.zeros(number_of_peepholes * hidden_size, dtype=np.float32)
            h_0 = params[H_0] if H_0 in params else np.zeros((batch_size, hidden_size), dtype=np.float32)
            c_0 = params[C_0] if C_0 in params else np.zeros((batch_size, hidden_size), dtype=np.float32)

            self.X = params[X]
            self.W = params[W]
            self.R = params[R]
            self.B = b
            self.P = p
            self.H_0 = h_0
            self.C_0 = c_0
        else:
            raise NotImplementedError()

    def f(self, x):  # type: (np.ndarray) -> np.ndarray
        return 1 / (1 + np.exp(-x))

    def g(self, x):  # type: (np.ndarray) -> np.ndarray
        return np.tanh(x)

    def h(self, x):  # type: (np.ndarray) -> np.ndarray
        return np.tanh(x)

    def step(self):  # type: () -> Tuple[np.ndarray, np.ndarray]
        [p_i, p_o, p_f] = np.split(self.P, 3)
        h_list = []
        H_t = self.H_0
        C_t = self.C_0
        for x in np.split(self.X, self.X.shape[0], axis=0):
            gates = np.dot(x, np.transpose(self.W)) + np.dot(H_t, np.transpose(self.R)) + np.add(
                *np.split(self.B, 2))
            i, o, f, c = np.split(gates, 4, -1)
            i = self.f(i + p_i * C_t)
            f = self.f(f + p_f * C_t)
            c = self.g(c)
            C = f * C_t + i * c
            o = self.f(o + p_o * C)
            H = o * self.h(C)
            h_list.append(H)
            H_t = H
            C_t = C
        concatenated = np.concatenate(h_list)
        if self.num_directions == 1:
            output = np.expand_dims(concatenated, 1)
        return output, h_list[-1]

input = np.array([[[1., 2., 3., 4.], [5., 6., 7., 8.]]]).astype(np.float32)

input_size = 4
hidden_size = 3
weight_scale = 0.1
number_of_gates = 4
number_of_peepholes = 3

node = onnx.helper.make_node(
    'LSTM',
    inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h'],
    outputs=['', 'Y'],
    hidden_size=hidden_size
)

# Initializing Inputs
X = input
W = weight_scale * np.ones((1, number_of_gates * hidden_size, input_size)).astype(np.float32)
R = weight_scale * np.ones((1, number_of_gates * hidden_size, hidden_size)).astype(np.float32)
B = np.zeros((1, 2 * number_of_gates * hidden_size)).astype(np.float32)
seq_lens = np.repeat(input.shape[0], input.shape[1]).astype(np.int32)
init_h = weight_scale * np.ones((1, input.shape[1], hidden_size)).astype(np.float32)
init_c = weight_scale * np.ones((1, input.shape[1], hidden_size)).astype(np.float32)

lstm = LSTM_Helper(X=X, W=W, R=R, B=B, initial_h=init_h, initial_c=init_c)
_, Y_h_1 = lstm.step()

node = onnx.helper.make_node(
'LSTM',
inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h', 'initial_c'],
outputs=['Y', 'Y_h', 'Y_c'],
hidden_size=hidden_size)

outputs = run_node(node, [X, W, R, B, seq_lens, init_h, init_c])
Y_h_2 = outputs["Y_h"]

Y_h_1_flattened = Y_h_1.flatten()
Y_h_2_flattened = Y_h_2.flatten()
absolute_error = np.abs(Y_h_1_flattened - Y_h_2_flattened)
max_rerr = np.max(absolute_error)
print("Y_h_1 == Y_h_2? " + str(max_rerr < 0.001))
```

`Y_h_1 == Y_h_2? True`

BTW,  class LSTM_Helper() is copied from https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/lstm.py

**Comment by chinhuang007** [comment] 2019-05-10 18:32
Close since the issue is fixed with https://github.com/onnx/onnx-tensorflow/pull/410

**Closed** 2019-05-10 18:38 UTC
